### ISSUE TITLE
Responsive flex layout works abnormally

### ISSUE THREAD

**Issue by StringKe** [mattrothenberg/react-overflow-list#3]
https://codesandbox.io/s/react-overflow-list-flex-error-u2b26?file=/src/App.tsx

When the current overflow container has no fixed size, the element will change the width of other containers

**Comment by mattrothenberg** [comment]
@StringKe The issue you're seeing is caused by the CSS you've added to the various elements on your page.

Keep in mind that the only styles that this library applies to the parent container are:

```css
display: flex;
flex-wrap: nowrap;
min-width: 0;
```
Here's a fork with some adjusted markup (I removed several of your nested `div.flex-1` elements.
https://codesandbox.io/embed/react-overflow-list-flex-error-forked-u18qg?fontsize=14&hidenavigation=1&theme=dark

**Comment by StringKe** [comment]
I have some dropmenu, overflow will affect them, is there any other way to solve it?

**Comment by StringKe** [comment]
https://codesandbox.io/s/react-overflow-list-flex-error-u2b26?file=/src/App.tsx
The complete code of my project about the layout
Is there any solution to it flickering?

**Comment by samwyzz** [comment]
@StringKe Hello, was wondering if any solution was found for the flickering issue ?
